### PR TITLE
Add/fix nice badges

### PR DESCRIPTION
**Pull request by szepeviktor**
Will you release this plugin as a Composer package?

### CODE REVIEW

**Comment by szepeviktor** [comment]
Looks great!

kép

**Comment by leonstafford** [comment]
> Will you release this plugin as a Composer package?

@szepeviktor - yes. Just pushed WP2Static out as package last week and will follow with this and any other repos. Doesn't look like any/many have pulled it from Packagist yet, but I'll add some notes for users on Composer-based WP. Any such provisioning methods you like?

**Comment by szepeviktor** [comment]
> Any such provisioning methods you like?

You can stuff a whole WP installation into one `composer.json`

- Packagist
- WPackagist
- GitHub repos
- ZIP files
- Composer plugins

and so on...

**Comment by szepeviktor** [comment]
e.g. https://github.com/szepeviktor/debian-server-tools/blob/master/webserver/wp-install/roots-composer.json

**Comment by leonstafford** [comment]
> e.g. https://github.com/szepeviktor/debian-server-tools/blob/master/webserver/wp-install/roots-composer.json

Perfect, thanks!

**Pull request merged**
